### ISSUE TITLE
Module ignores scene image format setting

### ISSUE THREAD

**Issue by ohanar** [VTTAssets/vtta-dndbeyond#227] opened 2020-06-24 23:25 UTC
If the scene image format is set to use the original image format, the module still uses webp. I tracked this down, to the fact that you do a strict equality [here](https://github.com/VTTAssets/vtta-dndbeyond/blob/master/src/messaging/type/add/page.js#L298), even though the setting is a string and the constant is a number.

**Comment by VTTAssets** [comment] 2020-06-25 09:15
Duplicate of #224

**Closed by VTTAssets** 2020-06-25 09:15 UTC
